### ISSUE TITLE
Privacy leakage in smart_contract.go

### ISSUE THREAD

**Issue by pdchecker** [TommyStarK/hyperledger-fabric-kubernetes#10]
In line 90, the private data is used as return value and will be included in the transaction and all peers can access it.

**Comment by TommyStarK** [comment]
Hi @pdchecker 

Thanks for the issue. Indeed you are right, there is a privacy leakage in the smart contract source code but it's intended. This repo should be considered as a dummy example and not production ready. I'm going to mention it the README.

**Comment by pdchecker** [comment]
您的来信我已收到！祝您生活愉快！
