### ISSUE TITLE
Do you create only one external builder service?

### ISSUE THREAD

**Issue by bh4rtp** [TommyStarK/hyperledger-fabric-kubernetes#4]
I have not had it running. The number of the external builder deployment is only one, i.e. `chaincode/demo.yaml`. And you configured three orgs. Mostly, every org will package it own chaincode and provide the external builder service. As for peer chaincode builder, one chaincode container is created for itself. Need we create an external builder service for every peer too?

**Comment by TommyStarK** [comment]
Hi @bh4rtp,

With Fabric 2.0, we are now able to separate the chaincode building and launching from the peer meaning the peer does not require a binding to docker.
As we must keep the same process for installing/approving and commit the chaincode, the Fabric dev team implemented the external chaincode builder feature.
By specifying your chaincode builder into the peer configuration you grant it the capability to treat external chaincode. 
What's happening under the hood is that the peer will try to treat the chaincode as external service and if it fails it will fallback to the default behavior with Docker.

The important part in chaincode as external service is the two files: connection.json and metadata.json in which you specify both that the chaincode is of type external as well as the endpoint on which the peer should communicate with the chaincode.

To answer your question, Yes the chaincode buildpack should be configured on each peer if you want it to be able to treat external chaincode.

Regarding my example, I only deploy one chaincode but Yes you could want to deploy multiple chaincodes but then you would have to perform the install/approve/commit phase multiple times.

Last but not the least, it's up to you and the blockchain network you want to set up, the chaincode buildpack could be used by all orgs and you could have only one instance of chaincode running. You could also want to have a specific buildpack and chaincode per org. It is up to you :) 

Hope it answers your question.

Best,

**Comment by TommyStarK** [comment]
From the fabric dev team

> As chaincode is supposed to be stateless and support multiple concurrent requests from a peer (and chaincode will support handling multiple concurrent requests as dictated by the language), then chaincode should be able to support multiple requests irrespective of where the request came from (so long as it's possible to point 2 peers in the same org to the same chaincode instance).

> The chaincode peer side registry has a single gRPC stream to some chaincode shim.  So, you can have a 1:n ratio of chaincode:peers  but you can't have a n:1 ratio.

Hope this is helpful.
Best,

**Comment by bh4rtp** [comment]
Yes, I concern about it. For my example, org1 has three peers, i.e. peer0, peer1, pee2.

I have tested to setup one external builder service for the three peers individually, i.e. chaincode-as-external-service-peer0org1, chaincode-as-external-service-peer1org1, chaincode-as-external-service-peer2org, how to deal with the deployment of chaincode on the three peers? Because they have different `connection.json`, and different `chaincode.tgz`, and then different chaincode id, need I approveformyorg three times every time specifying a single chaincode id? I have tested this way but failed.

Would you please give me some advices? Thanks.

> 
> Just keep in mind that if you have only one instance of chaincode running, you do have a single point of failure.
> 
> Hope this is helpful.
> Best,

**Comment by bh4rtp** [comment]
I have reported an issue: https://jira.hyperledger.org/browse/FAB-18444

**Comment by TommyStarK** [comment]
Problem is that you have a different connection file and thus different package ID. 

When the peer connects to the chaincode or the chaincode connects to the peer a single gRPC stream is instantiated and used meaning you cannot have multiple chaincodes bound to the same peer. 

There is a very interesting discussion ongoing on the fabric dev team slack channel. 

For now what I would do is the following: 
I will use the same chaincode for each peer in the same organization but not a single instance to avoid a single point of failure. To avoid this situation I will create a Kubernetes service that I will map to all chaincode instances and I will specify in the connection.json the service to communicate with. So for example let's say you 3 peers in org1. I will boot 3 chaincodes instances with the exact same package ID and let the kubernetes service round robin between the different chaincode pods. 
From the peer point of view, you only to perform the install approve commit one time. As you specified the k8s service endpoint in the connection.json, for the peer there is only one chaincode running where in facts you can have X chaincode pods running with the same configuration and let kubernetes routes the request. 

Not sure if it is perfectly clear

**Comment by TommyStarK** [comment]
Just keep in mind that Fabric is a framework and really cool one because it allows us to build the blockchain network we want to match the ecosystem that we want to represent. 

External chaincode is a team effort to remove the docker dependency and be able to have a network running in kubernetes without having to deal with the kubernetes CRI. 

It's a quite new feature and I am sure it will evolve in the future. 

I will come back to you on this thread If I have relevant info to share with you. 

Best,

**Comment by bh4rtp** [comment]
I have switched to one peer per org to one single external chaincode service, it does work. Thank you. It may cause single point failure sometimes but should be avaiable most time.
