### ISSUE TITLE
Error from server (BadRequest): pod cli.peer0.org1.dummy.com-64dd9ffb8-jsbr5 does not have a host assigned

### ISSUE THREAD

**Issue by rohitshukla11** [TommyStarK/hyperledger-fabric-kubernetes#7]
Hi,
I am getting this error "Error from server (BadRequest): pod cli.peer0.org1.dummy.com-64dd9ffb8-jsbr5 does not have a host assigned" after running this command "kubectl exec -it -n dummy-com $(kubectl get pod -n dummy-com -l component=cli.peer0.org1.dummy.com -o jsonpath="{.items[0].metadata.name}") -- bash" 
Please help!
Thanks

**Comment by TommyStarK** [comment]
Hi,

Has the pod `cli.peer0.org1.dummy.com` been correctly scheduled to a node ? Would you mind checking if the pod's state is `Running` ? If the pod isn't in a `Running` state you can describe to understand what went wrong.
Once your pod is in a `Running` state you can try again it should work.
Usually this error means that the pod couldn't be properly scheduled to a node, or it tool longer time, or asking for ressources the node cannot satisfy.

Best,

**Comment by TommyStarK** [comment]
@rohitshukla11 Your issue seems
to be related to Kubernetes so I am going to go ahead and close this issue. If you encounter any issue with my repo feel free to open an issue. 

Best,
