### ISSUE TITLE
getting tls bad certifiacte error

### ISSUE THREAD

**Issue by AmeerRiyaz** [TommyStarK/hyperledger-fabric-kubernetes#9]
when im trying to join channel using osnadmin im getting tls bad certificate error

**Comment by TommyStarK** [comment]
Hello,

Would you mind providing a bit more of context, logs ?

Best

**Comment by AmeerRiyaz** [comment]
yes sure 
I tried to modify a little your code for installing chaincode directly without using external cc 
While joining orderer to a channel in 2.5.4 im facing an error while peer is able to join 
Below is the command iam using for the joining orderer
 osnadmin channel join --channelID channelall --config-block channelall.block -o orderer0-dummy-com:9443 --ca-file /etc/hyperledger/fabric/crypto/ordererOrganizations/dummy.com/tlsca/tlsca.dummy.com-cert.pem --client-cert /etc/hyperledger/fabric/crypto/ordererOrganizations/dummy.com/orderers/orderer0.dummy.com/tls/server.crt --client-key /etc/hyperledger/fabric/crypto/ordererOrganizations/dummy.com/orderers/orderer0.dummy.com/tls/server.key
orderer logs and cli logs im provoiding 
![image](https://github.com/TommyStarK/hyperledger-fabric-kubernetes/assets/87801344/6f510f15-efbe-4519-96eb-f8b33676d2c1)


![image](https://github.com/TommyStarK/hyperledger-fabric-kubernetes/assets/87801344/64776ec4-e99b-4c4a-b762-83ca7245f978)

Thanks and Regards 
Ameer

**Comment by AmeerRiyaz** [comment]
Hello , 
Can you please guide me through this

**Comment by TommyStarK** [comment]
Without the modifications you introduced it is going to be hard for me to help you. What I can recommend is first to verify the tls artefacts you are using with openssl.  Be sure to check the generated crypto material in the crypto config volume.Also you would want to exec into orderers and peers and look at the tls material they are using.

**Comment by AmeerRiyaz** [comment]
can u guide me how do i copy my local certificates generated by fabric-ca into the particular location pod

**Comment by TommyStarK** [comment]
The simplest way is to create a secret from the files and mount this secret as volume to your pods. Please refer to the Kubernetes documentation to achieve that.

I am going to go ahead and close this issue as it seems to be related to your modifications and not the original project. This repository aims to provide a tutorial of how to use chaincode as an external service for a Fabric network running in Kubernetes. Please open an issue if you encounter any trouble with the tutorial as it is. 

Best
